language: java
services: docker
deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

env:
  global:
  - secure: UCpOMytLaOPcPdlnCpsX9CoahhcZz7dulZ8i1mGVvWcZm4XA47qLU6Q8vFqpMb8oIuqqLH8odN6wg7nHl48N6JN2JeSmQdOVAYxrxSlJTbx1PFj4G4DO3pm1mrsVpwauLEXpp5vI4q3YXM2TmDFPNYTcRhtfdhL4UQyDl3n8/27Yf0UD+JLmxQtLCGkn9b2DvYvKiZ2Mf/eOzS8EV+q7lh3JRcQg73HT8eDZqff4EN7UQKTQK0hzN6WxIcH00gBj9N+df9pB4EJPtAWIke14ztzN2dfEBK40v2lPGSijiD874uRzXNc5z9oGZmtJt/Rg5V8SeMBUZgeLPaElt3QbtkbkcU/y4A2e5g96UL8/HEk7Aufxemyb9TRaF8sNv3tjoPSDbpWSfwHt4+2FeWZBbfGZLHsszu+FBhkq+Dv1qF2WoPJvybveSWWx3A6LwIPzWyG5rlM7paFCa7hcsSf0AD39gSe5/akXOB8ILRtcVtFzdDMBX/6qnCbt0XfjsxhEhj/IIgC0vzVGHoihBvJzcjXgFza7rVKSDhOLM1Ev/nc7sOSPXplVaWaJ2JHVeXbxRgG3MOLW5jneZpud/msrPLRDGF2WqIf/THl0v/zfv2xfcpksIh2JCEq3kRo2HywwSVb8K2WYN0W7iL0Av66Vx5dAIBJeYjcAlRoVCs3d/jg=
  - secure: WcK1VEjvz4kxDoV+1gDyRZozJADqJVpLFrAE3OuYYv2gj0DXs4inqBVk8f3cDeqOPMOsohr/XOTNiZIMAZexsC7z4W/ok1gYnL/loac/rLuvZT6e7o3IsmYhR/BVacuv4RDNP3HjpxLz4d+hVFgeZnJwYCVL+Sc8+Ofn2YX+z7ioWjI3Ra4c/d5YNlnibWetnn/u/05KtqdRwr09Qp1Qz1f2LAuDeZqiMLlehtmYPftFIccD0xLyxeDHhemvcuePVBiTk8dKlYcV7rznAR+dTQjSCSgzvt9ZIwUg8YB929YI7/aPLNyj1yGcM3NjvPRp3MxOy0gY7qgyNfXW131ebgFeiI9EnUqO4ibXIw/qMI5lEjyZOy/BXr5EW9jzLlFpgp72SIfr9HD55Iinzyu3hqTR6IDDnyFcUonrZXPRZY+Hs3TCjCv5u1eqouEHS5GlEPweikOd7HT0QyqRwjnGrAp6s0/MUvHB+01VEQKw43Flx2FH8EWYADcwZlrWWgW+DpZwXNQiZFQc1q43vE3f+s/btGEkyY8zwJnoSA8QtzMIy/b8f8Y6KB0scSpWyjNEH+VlbDKWi33vL5+k6ULw6yN5MiofFvIpxRr2hotMO5JuGhp0GNj7fHU4hqF58WC51MHj7uf58bKZzuZqAwg2cixdSR0IKlzbVrl9PejsJ+Q=
